import { colors } from "../constants/colors";

export const typo = {
    titler:{
        fontSize:40,
        fontWeight:'bold',
        color:colors.greyDeep,
        textTransform:'uppercase',
        alignSelf:'center'
    },
    h1:{
        fontSize:20,
        fontWeight:'bold',
        color:colors.theme,
        textTransform:'uppercase',
        alignSelf:'center'
    },
    h2:{
        fontSize:18,
        fontWeight:'bold',
        color:colors.theme,
        textTransform:'uppercase',
        alignSelf:'center'
    },
    h3:{
        fontSize:16,
        fontWeight:'bold',
        color:colors.theme,
        textTransform:'uppercase',
        alignSelf:'center'
    },
    h4:{
        fontSize:14,
        fontWeight:'bold',
        color:colors.theme,
        textTransform:'uppercase',
        alignSelf:'center'
    },
    h1r:{
        fontSize:20,
        fontWeight:'bold',
        color:colors.greyDeep,
        textTransform:'uppercase',
        alignSelf:'center'
    },
    h2r:{
        fontSize:18,
        fontWeight:'bold',
        color:colors.greyDeep,
        textTransform:'uppercase',
        alignSelf:'center'
    },
    h3r:{
        fontSize:16,
        fontWeight:'bold',
        color:colors.greyDeep,
        textTransform:'uppercase',
        alignSelf:'center'
    },
    h4r:{
        fontSize:14,
        fontWeight:'bold',
        color:colors.greyDeep,
        textTransform:'uppercase',
        alignSelf:'center'
    },
    p:{
        fontSize:14,
        fontWeight:'bold',
        color:colors.greyDeep
    }
}